export default [
    {
        id: '1',
        img: '/img/AnejoHighball.jpg',
        cocktailName: 'Añejo Highball',
        shortDescription: 'Añejo - old rum, really makes this drink.',
        category: 'Cocktail',
        glass: 'Highball',
        instructions: 'Build the rum, curaçao, lime juice, and bitters in a highball glass filled with ice. Top with ginger beer.',
        ingredient1: 'Orange curaçao liqueur',
        ingredient2: 'Añejo rum',
        ingredient3: 'Aromatic bitters',
        ingredient4: 'Ginger',
    },
    {
        id: '11',
        img: '/img/japanese-slipper-recipe-759710-hero-1-8e956a8fd6994083bb3745d71da9587a.jpg',
        cocktailName: 'Japanese Slipper',
        shortDescription: 'Light on the alcohol and packed with fruity flavor.',
        category: 'Cocktail',
        glass: 'Martini',
        instructions: 'In a cocktail shaker filled with ice, pour the melon and orange liqueurs and lemon juice.',
        ingredient1: 'Melon Liqueuer',
        ingredient2: 'Premium triple sec',
        ingredient3: 'Freshly squeezed lemon juice',
        ingredient4: 'Melon slice or ball,',
    },
    {
        id: '2',
        img: '/img/alabama-slammer-recipe-hero-images-1-ed9e4029034945a392bc306df6ae4a3b.jpg',
        cocktailName: 'Alabama Slammer',
        shortDescription: 'Orange juice and Southern Comfort',
        category: 'Cocktail',
        glass: 'Highball',
        instructions: 'Pour the Southern Comfort, amaretto, sloe gin, and orange juice in a cocktail shaker. Garnish with an orange wheel and cherry.',
        ingredient1: 'Southern Comfort',
        ingredient2: 'Amaretto liqueur',
        ingredient3: 'Sloe gin',
        ingredient4: 'Orange juice',
    },
    {
        id: '3',
        img: '/img/aviation-cocktail-recipe-760055-hero-01-af5233300c184476b02891de2c685b2a.jpg',
        cocktailName: 'Aviation',
        shortDescription: 'Lightly floral and sweet taste.',
        category: 'Cocktail',
        glass: 'Martini',
        instructions: 'Pour the gin, liqueurs, and lemon juice into a cocktail shaker filled with ice. Shake well. Strain into a chilled cocktail glass.',
        ingredient1: 'Gin',
        ingredient2: 'Maraschino Liqueur',
        ingredient3: 'C​rème de violette liqueur',
        ingredient4: 'Lemon juice',
    },
    {
        id: '4',
        img: '/img/bay-breeze-recipe-761000-14-5b45054946e0fb0037c4bd0c.jpg',
        cocktailName: 'Bay Breeze',
        shortDescription: 'Tropical taste of a pineapple',
        category: 'Cocktail',
        glass: 'Highball',
        instructions: 'Pour the vodka into an ​ice-filled highball glass. Top with equal amounts of pineapple and cranberry juices.',
        ingredient1: 'Vodka',
        ingredient2: 'Pineapple juice',
        ingredient3: 'Cranberry juice',
        ingredient4: 'Lime wedge, for garnish',
    },
    {
        id: '5',
        img: '/img/black-velvet-recipe-759594-step-04-3-f623e1cba1f345be9b40756df3f8c6ce.jpg',
        cocktailName: 'Black Velvet',
        shortDescription: '​​Champagne and dark beer in a single glass',
        category: 'Cocktail',
        glass: 'Wine flute',
        instructions: 'Pour the Champagne into a wine flute, filling the glass about halfway. Slowly pour the stout on top to fill the glass. Serve and enjoy.',
        ingredient1: 'Champagne',
        ingredient2: 'Stout',
    },
    {
        id: '6',
        img: '/img/Norina-Cocktail-1cb7f230403349f2bd6d7eb341c93796.jpg',
        cocktailName: 'Bamboo Cocktail',
        shortDescription: 'Classic recipe that is a variation of the martini',
        category: 'Cocktail',
        glass: 'Martini',
        instructions: 'Gather the ingredients. Pour the vermouth, sherry, and bitters into a mixing glass filled with ice.',
        ingredient1: 'Dry vermouth',
        ingredient2: 'Orange bitters',
        ingredient3: 'Aromatic bitters',
        ingredient4: 'Sherry',
    },
    {
        id: '7',
        img: '/img/cape-codder-recipe-759287-hero-02-3a6a5296acf146c197a656adff8bbacb.jpg',
        cocktailName: 'Cape Codder',
        shortDescription: 'Great-tasting drink and a perfect choice for anytime',
        category: 'Cocktail',
        glass: 'Highball',
        instructions: 'In a highball glass with ice cubes, pour the vodka and cranberry juice. Stir well and Garnish with a lime wedge. Serve and enjoy.',
        ingredient1: 'Vodka',
        ingredient2: 'Cranberry juice',
        ingredient3: 'Lime Wedge',
    },
    {
        id: '8',
        img: '/img/DulceDeLeche-Cocktail-001-257ac8059db24b699d6d39a255c6e929.jpg',
        cocktailName: 'Dulce de Leche',
        shortDescription: 'A cocktail found in "Guys and Dolls."',
        category: 'Cocktail',
        glass: 'Highball',
        instructions: 'In a cocktail shaker filled with ice, pour the rum, chocolate liqueur, and sweetened condensed milk. Shake well.',
        ingredient1: 'Chocolate liqueur',
        ingredient2: 'sweetened condensed milk',
        ingredient3: 'Ground Cinnamon',
        ingredient4: 'Shaved Chocolate',
    },
    {
        id: '9',
        img: '/img/deep-blue-sea-martini-recipe-761040-hero-01-35639d01cecd4549a8577a0ed8c3859b.jpg',
        cocktailName: 'Deep Blue Sea',
        shortDescription: 'Intriguing sour tropical fruit flavor',
        category: 'Martini',
        glass: 'Highball',
        instructions: 'In a cocktail shaker filled with ice, pour the vodka, blue curaçao, sour mix, and pineapple juice. Strain into a chilled cocktail glass. Serve and enjoy.',
        ingredient1: 'Vodka',
        ingredient2: 'Blue curaçao liqueur',
        ingredient3: 'Sour mix',
        ingredient4: 'Pineapple',
    },
    {
        id: '10',
        img: '/img/grasshopper-cocktail-recipe-759305-hero-02-5c1d5e6246e0fb00018d87e8.jpg',
        cocktailName: 'Grasshopper',
        shortDescription: 'Delicious chocolate-mint cocktail',
        category: 'Cocktail',
        glass: 'Martini',
        instructions: "If you'd like to rim the glass, wet it with a quick dip in a shallow dish filled with either liqueur from the recipe. While still holding the glass upside down, roll the rim in a dish of grated chocolate, cocoa powder, or finely crushed graham crackers.",
        ingredient1: 'Grated chocolate',
        ingredient2: 'White crème de cacao liqueur',
        ingredient3: 'Cream',
        ingredient4: 'Green crème de menthe liqueur',
    },
    {
        id: '12',
        img: '/img/ZombiesBrew-GettyImages-152831178-574ed72c5f9b585165a5f6cd.jpg',
        cocktailName: 'Zombies Brew',
        shortDescription: 'A simple mix of vodka, Three Olives Tartz',
        category: 'Cocktail',
        glass: 'Highball',
        instructions: 'Pour the vodka, triple sec, and lemonade into a cocktail shaker, and fill with ice. Shake well. Strain into a chilled cocktail glass.',
        ingredient1: 'Vodka',
        ingredient2: 'Three Olives',
        ingredient3: 'Triple Sec',
        ingredient4: 'Lemonade',
    }
    ];